### ISSUE TITLE
Simulation script cancel all paid donations ( it should not do that)

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-1-simulation#35]

**Comment by mohammadranjbarz** [comment]
@MoeNick 
it's not related to Giveth/giveth-dapp#2109
it an old bug that we knew it recently

**Comment by mohammadranjbarz** [comment]
@MoeNick 
Steps for testing this issue:
1. Create a milestone
2. Donate to it
3. Collect donations
4. Create a new donation
5. After cancelling milestone, the collected donation should remain `Paid` or `Processing` and the new donation should become `cancelled`

**Comment by MoeNick** [comment]
https://develop.giveth.io/milestone/mytest-17ap

**Comment by mohammadranjbarz** [comment]
@MoeNick 
You can check that after cancelling, `processing` donations didn't become `Cancelled`
